name       : perl-module-build
version    : '0.4231'
release    : 11
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-0.4231.tar.gz : 7e0f4c692c1740c1ac84ea14d7ea3d8bc798b2fb26c09877229e04f430b2b717
homepage   : https://metacpan.org/release/Module-Build
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Build and install Perl modules
description: |
    Module::Build is a system for building, testing, and installing Perl modules. It is meant to be an alternative to ExtUtils::MakeMaker. Developers may alter the behavior of the module through subclassing in a much more straightforward way than with MakeMaker. It also does not require a make on your system - most of the Module::Build code is pure-perl and written in a very cross-platform way.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
