name       : perl-module-build
version    : 0.4224
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-0.4224.tar.gz : a6ca15d78244a7b50fdbf27f85c85f4035aa799ce7dd018a0d98b358ef7bc782
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Build and install Perl modules
description: |
    Module::Build is a system for building, testing, and installing Perl modules. It is meant to be an alternative to ExtUtils::MakeMaker. Developers may alter the behavior of the module through subclassing in a much more straightforward way than with MakeMaker. It also does not require a make on your system - most of the Module::Build code is pure-perl and written in a very cross-platform way.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
